apiVersion: v1
kind: Service
metadata:
  name: predict-teacher-churn
spec:
  type: NodePort
  selector:
    app: predict-teacher-churn
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080